# Generated by Django 2.1.1 on 2018-10-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=30)),
                ('razaMascota', models.CharField(max_length=30)),
                ('descMascota', models.CharField(max_length=100)),
                ('estadoMascota', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=20)),
                ('apellidoPersona', models.CharField(max_length=20)),
            ],
        ),
    ]
