# Generated by Django 2.1.1 on 2018-10-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descMascota',
            field=models.TextField(max_length=100),
        ),
    ]
