# Generated by Django 2.1.1 on 2018-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20181027_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descMascota',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
