# Generated by Django 2.1.1 on 2018-10-28 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sistema', '0004_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='perfil',
            field=models.CharField(default='Invitado', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
