# Generated by Django 2.1.1 on 2018-11-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_mascota_fotomascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.FileField(upload_to='fotos/'),
        ),
    ]
