# Generated by Django 2.1.1 on 2018-11-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0015_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.CharField(max_length=70),
        ),
    ]
