# Generated by Django 2.1.1 on 2018-11-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0020_auto_20181108_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipoPersona',
            field=models.CharField(default='Usuario', max_length=50),
        ),
    ]
