# Generated by Django 2.1.1 on 2018-11-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_auto_20181106_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellidoPersona',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombrePersona',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='perfil',
        ),
    ]
