# Generated by Django 2.1.1 on 2018-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0017_remove_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipoPersona',
            field=models.CharField(default='Adoptante', max_length=50),
        ),
    ]
