# Generated by Django 2.1.1 on 2018-11-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0018_auto_20181108_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
